output: Reference
clean: false
sdk: iphone
author: Valery Bashkatov
author_url: http://valery.bashkatov.org
github_url: https://github.com/valery-bashkatov/Crypto
module: Crypto
readme: README.md
min_acl: public
theme: fullwidth